name: weatherapi_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 9.0.0
  http: ^0.13.4
  material_floating_search_bar: ^0.3.6



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:


  uses-material-design: true


